/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendataan;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
/**
 *
 * @author Prio Arief G
 */
public class utama extends javax.swing.JFrame {

    
    public utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane() {
            Image image = new ImageIcon(
                getClass().getResource("/gambar/background.jpg")).getImage();

            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, this.getWidth(),
                    this.getHeight(), null);
            }
        };
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        Jurusan = new javax.swing.JMenu();
        DataJurusan = new javax.swing.JMenuItem();
        Siswa = new javax.swing.JMenu();
        DataSiswa = new javax.swing.JMenuItem();
        LAB = new javax.swing.JMenu();
        DataLAB = new javax.swing.JMenuItem();
        Nilai = new javax.swing.JMenu();
        DataNilai = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Jurusan.setText("Jurusan");

        DataJurusan.setText("Data Jurusan");
        DataJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataJurusanActionPerformed(evt);
            }
        });
        Jurusan.add(DataJurusan);

        jMenuBar1.add(Jurusan);

        Siswa.setText("Siswa");

        DataSiswa.setText("Data Siswa");
        DataSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataSiswaActionPerformed(evt);
            }
        });
        Siswa.add(DataSiswa);

        jMenuBar1.add(Siswa);

        LAB.setText("LAB");

        DataLAB.setText("Data LAB");
        DataLAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataLABActionPerformed(evt);
            }
        });
        LAB.add(DataLAB);

        jMenuBar1.add(LAB);

        Nilai.setText("Nilai");

        DataNilai.setText("Data Nilai");
        DataNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataNilaiActionPerformed(evt);
            }
        });
        Nilai.add(DataNilai);

        jMenuBar1.add(Nilai);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataSiswaActionPerformed
        siswa e = new siswa();
        e.show();
    }//GEN-LAST:event_DataSiswaActionPerformed

    private void DataLABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataLABActionPerformed
        lab e = new lab();
        e.show();
    }//GEN-LAST:event_DataLABActionPerformed

    private void DataNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataNilaiActionPerformed
        nilai e = new nilai();
        e.show();
    }//GEN-LAST:event_DataNilaiActionPerformed

    private void DataJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataJurusanActionPerformed
        jurusan e = new jurusan();
        e.show();
    }//GEN-LAST:event_DataJurusanActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new utama().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DataJurusan;
    private javax.swing.JMenuItem DataLAB;
    private javax.swing.JMenuItem DataNilai;
    private javax.swing.JMenuItem DataSiswa;
    private javax.swing.JMenu Jurusan;
    private javax.swing.JMenu LAB;
    private javax.swing.JMenu Nilai;
    private javax.swing.JMenu Siswa;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
